// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SimFC23",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SimFC23",
            targets: ["AppModule"],
            bundleIdentifier: "com.advaitconty.simfc23.alpha",
            teamIdentifier: "5S5Y9ZY58F",
            displayVersion: "0.1alpha",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .gamepad),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .sportsGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)